# TALENT SOURCING
   
In this notebook, a talent sourcing company first screens the available candidates on a set of specific job title key words to identify and rank the candidates based on their job titles. By looking at the resulting list of ranked candidates, a preferred candidate is selected and the list is ranked again based on the job title as well as the location of the preferred candidate.

Data Attributes:   
id : unique identifier for candidate (numeric)   
job_title : job title for candidate (text)   
location : geographical location for candidate (text)   
connections: number of connections candidate has, 500+ means over 500 (text)   
Output (desired target):   
fit - how fit the candidate is for the role? (numeric, probability between 0-1)   
Keywords: “Aspiring human resources” or “seeking human resources”

In [1]:
import gensim
import pandas as pd

In [2]:
df = pd.read_csv('potential-talents - Aspiring human resources - seeking human resources.csv')
df.head()

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,NaN
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,NaN
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,NaN
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,NaN
4,5,Advisory Board Member at Celal Bayar University,"Ä°zmir, TÃ¼rkiye",500+,NaN

In [22]:
#replace the misspelt location entries
df.replace({'Ä°zmir, TÃ¼rkiye': 'İzmir, Türkiye', 'Kanada' : 'Canada'}, inplace=True) #replace the spelling with incorrect characters

In [23]:
df.head()

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.497849
1,2,Native English Teacher at EPIK (English Progra...,Canada,500+,0.372279
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.927214
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,0.705831
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,0.463202

In [24]:
df.shape

(104, 5)

In [25]:
df.job_title[0]

'2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional'

In [26]:
from sentence_transformers import SentenceTransformer

In [27]:
#initialize model
model = SentenceTransformer('bert-base-nli-mean-tokens')

In [28]:
import numpy as np

In [29]:
#create an array of the job titles
job_titl = np.array(df.job_title)
job_titl

array(['2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional',
       'Native English Teacher at EPIK (English Program in Korea)',
       'Aspiring Human Resources Professional',
       'People Development Coordinator at Ryan',
       'Advisory Board Member at Celal Bayar University',
       'Aspiring Human Resources Specialist',
       'Student at Humber College and Aspiring Human Resources Generalist',
       'HR Senior Specialist',
       'Student at Humber College and Aspiring Human Resources Generalist',
       'Seeking Human Resources HRIS and Generalist Positions',
       'Student at Chapman University',
       'SVP, CHRO, Marketing & Communications, CSR Officer | ENGIE | Houston | The Woodlands | Energy | GPHR | SPHR',
       'Human Resources Coordinator at InterContinental Buckhead Atlanta',
       '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional',
       '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional',
       'Native English Teacher at EPIK (English Program in Korea)',
       'Aspiring Human Resources Professional',
       'People Development Coordinator at Ryan',
       '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional',
       'Native English Teacher at EPIK (English Program in Korea)',
       'Aspiring Human Resources Professional',
       'People Development Coordinator at Ryan',
       'Advisory Board Member at Celal Bayar University',
       'Aspiring Human Resources Specialist',
       'Student at Humber College and Aspiring Human Resources Generalist',
       'HR Senior Specialist',
       'Aspiring Human Resources Management student seeking an internship',
       'Seeking Human Resources Opportunities',
       'Aspiring Human Resources Management student seeking an internship',
       'Seeking Human Resources Opportunities',
       '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional',
       'Native English Teacher at EPIK (English Program in Korea)',
       'Aspiring Human Resources Professional',
       'People Development Coordinator at Ryan',
       'Advisory Board Member at Celal Bayar University',
       'Aspiring Human Resources Specialist',
       'Student at Humber College and Aspiring Human Resources Generalist',
       'HR Senior Specialist',
       'Student at Humber College and Aspiring Human Resources Generalist',
       'Seeking Human Resources HRIS and Generalist Positions',
       'Student at Chapman University',
       'SVP, CHRO, Marketing & Communications, CSR Officer | ENGIE | Houston | The Woodlands | Energy | GPHR | SPHR',
       'Human Resources Coordinator at InterContinental Buckhead Atlanta',
       '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional',
       'Native English Teacher at EPIK (English Program in Korea)',
       'Aspiring Human Resources Professional',
       'People Development Coordinator at Ryan',
       'Advisory Board Member at Celal Bayar University',
       'Aspiring Human Resources Specialist',
       'Student at Humber College and Aspiring Human Resources Generalist',
       'HR Senior Specialist',
       'Student at Humber College and Aspiring Human Resources Generalist',
       'Seeking Human Resources HRIS and Generalist Positions',
       'Student at Chapman University',
       'SVP, CHRO, Marketing & Communications, CSR Officer | ENGIE | Houston | The Woodlands | Energy | GPHR | SPHR',
       'Human Resources Coordinator at InterContinental Buckhead Atlanta',
       '2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional',
       'Aspiring Human Resources Professional',
       'People Development Coordinator at Ryan',
       'Aspiring Human Resources Specialist', 'HR Senior Specialist',
       'Seeking Human Resources HRIS and Generalist Positions',
       'Student at Chapman University',
       'SVP, CHRO, Marketing & Communications, CSR Officer | ENGIE | Houston | The Woodlands | Energy | GPHR | SPHR',
       'Human Resources Coordinator at InterContinental Buckhead Atlanta',
       'Experienced Retail Manager and aspiring Human Resources Professional',
       'Human Resources, Staffing and Recruiting Professional',
       'Human Resources Specialist at Luxottica',
       'Director of Human Resources North America, Groupe Beneteau',
       'Retired Army National Guard Recruiter, office manager,  seeking a position in Human Resources.',
       'Human Resources Generalist at ScottMadden, Inc.',
       'Business Management Major and Aspiring Human Resources Manager',
       'Aspiring Human Resources Manager, seeking internship in Human Resources.',
       'Human Resources Professional',
       'Nortia Staffing is seeking Human Resources, Payroll & Administrative Professionals!!  (408) 709-2621',
       'Aspiring Human Resources Professional | Passionate about helping to create an inclusive and engaging work environment',
       'Human Resources|\nConflict Management|\nPolicies & Procedures|Talent Management|Benefits & Compensation',
       "Human Resources Generalist at Schwan's",
       'Liberal Arts Major. Aspiring Human Resources Analyst.',
       'Junior MES Engineer| Information Systems',
       'Senior Human Resources Business Partner at Heil Environmental',
       'Aspiring Human Resources Professional | An energetic and Team-Focused Leader',
       'HR Manager at Endemol Shine North America',
       'Human Resources professional for the world leader in GIS software',
       'RRP Brand Portfolio Executive at JTI (Japan Tobacco International)',
       'Information Systems Specialist and Programmer with a love for data and organization.',
       'Bachelor of Science in Biology from Victoria University of Wellington',
       'Human Resources Management Major',
       'Director Human Resources  at EY',
       'Undergraduate Research Assistant at Styczynski Lab',
       'Lead Official at Western Illinois University',
       'Seeking employment opportunities within Customer Service or Patient Care',
       'Admissions Representative at Community medical center long beach',
       'Seeking Human  Resources Opportunities. Open to travel and relocation.',
       'Student at Westfield State University',
       'Student at Indiana University Kokomo - Business Management - \nRetail Manager at Delphi Hardware and Paint',
       'Aspiring Human Resources Professional', 'Student',
       'Seeking Human Resources Position',
       'Aspiring Human Resources Manager | Graduating May 2020 | Seeking an Entry-Level Human Resources Position in St. Louis',
       'Human Resources Generalist at Loparex',
       'Business Intelligence and Analytics at Travelers',
       'Always set them up for Success',
       'Director Of Administration at Excellence Logging'], dtype=object)

In [30]:
#encode/embed the job titles
sentence_embeddings = model.encode(job_titl)

In [31]:
sentence_embeddings.shape

(104, 768)

In [32]:
#embed key phrase e.g. “Aspiring human resources” 
key_wd = model.encode('Aspiring human resources')
key_wd

array([ 4.86833394e-01, -5.93161099e-02,  2.59112954e+00,  7.33451188e-01,
        4.49116886e-01,  5.04019976e-01,  3.63583341e-02, -4.39902842e-01,
        7.15804875e-01, -7.55716443e-01, -4.22236502e-01,  7.80875564e-01,
        8.47344697e-01,  3.68243396e-01, -2.28280857e-01, -2.29795933e-01,
        1.86412290e-01, -4.40084875e-01,  7.81652391e-01, -1.43286061e+00,
       -5.99061847e-01,  4.20602337e-02,  8.05639744e-01, -7.93278813e-01,
        4.04325575e-01, -8.06080341e-01, -7.83224821e-01, -1.12466478e+00,
        1.02175951e-01,  2.55557477e-01, -2.97143131e-01, -6.94274247e-01,
       -1.85472786e-01, -1.10916749e-01, -4.57902282e-01,  5.98485112e-01,
        7.21237063e-01,  3.14758360e-01, -7.26479888e-02, -1.26594320e-01,
        6.04229331e-01,  2.37531707e-01,  2.55630553e-01,  6.91818118e-01,
       -1.03937173e+00, -2.71681786e-01, -8.89906704e-01, -2.00816728e-02,
        2.66709864e-01, -1.21575499e+00, -7.33241677e-01,  6.40898719e-02,
       -3.49752247e-01,  2.07825258e-01, -7.46391177e-01,  2.92764753e-01,
        1.00526547e+00, -1.48307025e+00,  3.18140745e-01,  8.44529986e-01,
       -6.71435237e-01, -1.11308262e-01,  5.65927625e-01,  9.09563363e-01,
        8.18828940e-02, -1.51950745e-02,  9.17958081e-01, -5.05006492e-01,
       -3.23078007e-01, -2.59628147e-01,  6.12606183e-02,  7.98359960e-02,
        2.03913301e-01,  6.59417689e-01, -1.65349805e+00, -5.60479701e-01,
        4.08023447e-01,  8.09907436e-01,  1.28832591e+00,  9.54596162e-01,
        7.45323002e-01,  4.45980698e-01,  6.95496380e-01,  7.49926716e-02,
       -1.92682142e-03,  8.58580410e-01,  1.32880306e+00,  1.69025356e-04,
       -1.81065273e+00,  5.17890036e-01,  2.24537845e-03, -2.71626234e-01,
        1.04644454e+00, -1.97690818e-02,  1.15408704e-01,  7.33580470e-01,
        3.73032421e-01, -6.32292271e-01,  4.16780472e-01, -3.97573672e-02,
        3.40940416e-01,  4.72694963e-01, -5.89543402e-01, -1.53715923e-01,
       -1.01904139e-01,  3.48089308e-01,  5.91687635e-02, -4.40345407e-02,
       -1.08476567e+00,  6.32584095e-03, -9.93280262e-02, -5.64667583e-02,
        3.94342005e-01,  2.54684687e-01, -6.80170674e-03, -1.12903796e-01,
       -1.41009927e+00,  2.14953870e-01,  3.04064393e-01,  3.73297542e-01,
        7.45979324e-02,  6.61378026e-01, -1.37512490e-01, -9.01942849e-01,
        8.37321654e-02,  4.43014771e-01,  5.15932202e-01,  3.77570033e-01,
        1.65586136e-02, -2.16974229e-01, -1.32053969e-02,  2.69224495e-01,
        2.44483799e-01, -4.62589085e-01,  1.97064076e-02,  2.96611995e-01,
       -3.39749992e-01,  2.19005495e-01,  1.86672896e-01,  6.44122779e-01,
       -3.76125246e-01, -2.40031928e-01,  1.06738544e+00, -1.64498895e-01,
       -6.76179528e-02, -3.71442735e-01,  4.85994428e-01,  2.22622976e-02,
       -5.35256326e-01,  4.79132354e-01, -6.69607282e-01,  3.68527591e-01,
       -7.70859063e-01, -5.60178757e-01, -1.07298064e+00,  2.36500613e-02,
        1.04784844e-02, -3.60367715e-01,  4.92782891e-02,  1.22119708e-03,
       -3.39381516e-01,  1.44913793e+00, -1.70022950e-01,  4.86199379e-01,
       -2.21054643e-01, -3.49641412e-01,  5.01128554e-01, -1.90868303e-01,
        5.39337456e-01,  3.60040553e-02,  6.10070884e-01, -7.09267974e-01,
        3.84197474e-01,  1.41300231e-01,  6.45220160e-01, -4.95141655e-01,
        3.52023244e-01,  2.00289294e-01,  3.32869887e-01, -7.20911026e-01,
        5.53087473e-01,  3.77789080e-01,  3.52684851e-03, -3.94564390e-01,
       -1.10199594e+00, -7.85446644e-01, -7.21773624e-01, -7.04291761e-02,
        7.45095164e-02, -5.58072448e-01,  9.31371897e-02, -3.05780858e-01,
       -2.56088018e-01, -1.14968491e+00,  4.82736915e-01,  2.22944334e-01,
        3.61241490e-01,  8.81039321e-01,  6.85296357e-02,  3.38089317e-01,
        1.07111001e+00, -1.26676643e+00,  1.76051617e-01,  6.56320870e-01,
       -3.66871417e-01,  6.14956141e-01,  6.75827444e-01,  3.73648345e-01,
       -4.34838206e-01, -1.03715253e+00,  2.75407016e-01,  4.95115101e-01,
        5.52586913e-01, -4.79726702e-01,  1.39381304e-01, -4.16517079e-01,
        5.57729661e-01,  2.68016458e-01, -4.60534275e-01,  1.45617887e-01,
        1.90173745e+00,  5.95562682e-02,  1.07709908e+00,  5.91766000e-01,
       -5.52315235e-01,  1.24621883e-01,  5.45472026e-01, -7.85297036e-01,
       -7.90785491e-01, -1.26235113e-01,  5.01285672e-01,  5.69706321e-01,
       -4.83855084e-02, -1.00071952e-01, -3.11315238e-01,  8.21937323e-02,
       -1.13792384e+00,  2.81117022e-01,  2.28135660e-01, -9.82941985e-02,
        2.62214273e-01,  1.08359921e+00,  1.94564313e-01,  8.88105869e-01,
       -9.83239949e-01, -4.58513081e-01,  8.31802011e-01, -2.88237751e-01,
       -5.67914188e-01,  4.45957661e-01, -7.71562457e-01, -5.78839898e-01,
       -5.35564244e-01, -5.55517077e-02, -2.47237124e-02, -4.46351528e-01,
       -5.16321719e-01, -6.02834344e-01,  3.91541094e-01, -2.56492198e-01,
        2.16973662e-01,  1.63749009e-01, -1.03250051e+00, -1.40570045e-01,
        5.19799478e-02, -9.94277477e-01, -2.19942242e-01, -2.58123308e-01,
       -1.80273086e-01,  7.99916267e-01, -6.04504108e-01,  3.26896548e-01,
       -9.31914076e-02,  6.00526109e-02,  7.39286244e-01,  3.87464389e-02,
        1.77770007e+00, -2.66487807e-01, -2.53306270e-01,  2.13442773e-01,
       -6.81576550e-01, -9.94731039e-02, -2.15773058e+00, -7.00900197e-01,
        3.36455941e-01,  1.72382265e-01,  7.08415806e-02,  4.02392447e-01,
       -2.59434342e-01, -3.98313433e-01, -6.76920891e-01, -1.80894971e-01,
       -2.47643039e-01, -3.20915282e-01,  1.74123824e+00, -3.79857719e-01,
        4.88907039e-01,  2.94869542e-01, -9.79831338e-01,  5.08295000e-02,
       -6.99210107e-01,  4.64257479e-01, -1.25902236e+00, -1.22190237e-01,
        6.32005811e-01, -3.85013148e-02,  8.28733444e-01,  7.49518499e-02,
       -8.36558044e-01, -6.82970762e-01, -9.24860954e-01,  5.93220666e-02,
       -2.19693631e-01, -1.04072118e+00, -2.78546244e-01,  6.12784922e-01,
       -1.06855668e-01, -6.28777325e-01,  1.11225057e+00,  2.87859887e-01,
       -7.45472074e-01,  4.14297506e-02, -1.44401073e-01,  3.78870010e-01,
        2.14095190e-01,  1.18079662e+00,  9.05881673e-02,  2.94811666e-01,
       -3.58042538e-01, -1.00054063e-01,  1.95723265e-01, -6.91523701e-02,
        3.59110832e-01, -5.48992515e-01, -2.81640679e-01,  9.92280185e-01,
       -1.78671941e-01, -9.94703412e-01,  3.04559410e-01,  3.15305501e-01,
        3.40663314e-01,  7.52286494e-01, -3.42068136e-01, -1.36937201e-02,
        1.26886678e+00, -6.31421447e-01,  4.64367241e-01, -1.02752995e+00,
       -1.19329825e-01,  2.85615683e-01, -5.25254548e-01,  9.95273963e-02,
       -2.76238862e-02, -1.38935149e-01,  1.02307796e-02, -2.38105301e-02,
        5.76542318e-01,  1.57508284e-01, -5.74211255e-02, -2.18982428e-01,
        2.78872311e-01, -1.62087709e-01, -2.35406563e-01, -3.03212732e-01,
        4.08147901e-01, -5.97342610e-01,  9.68485028e-02,  4.58952606e-01,
        8.94885540e-01,  2.34570950e-01, -6.14362359e-02, -1.04391563e+00,
       -5.99710226e-01, -1.59578890e-01, -4.20384467e-01, -1.17943706e-02,
       -1.36433050e-01, -1.25632632e+00,  1.73558235e-01, -3.57306212e-01,
        7.46421874e-01, -1.03447843e+00, -3.09008360e-01, -3.77012044e-01,
        6.08382583e-01,  2.16685340e-01, -1.09499991e-01, -2.47900486e-01,
        6.11900926e-01,  1.08191684e-01,  1.10900247e+00, -8.99594426e-02,
        8.43698502e-01,  2.90411651e-01,  4.20208365e-01, -8.92280459e-01,
        3.97702098e-01,  8.54970455e-01,  3.37000526e-02, -1.82392389e-01,
        5.52292168e-01,  2.81243533e-01,  1.10377276e+00,  5.51560342e-01,
        4.54364300e-01, -2.92453974e-01,  3.72028172e-01, -3.96798432e-01,
       -1.22057188e+00,  5.42110279e-02, -1.12919962e+00,  6.81897998e-01,
        6.91445053e-01,  2.21576601e-01, -5.98726869e-01,  9.95042697e-02,
        9.43656266e-01, -1.52470505e+00,  9.85363841e-01,  1.85706452e-01,
       -5.34738302e-01,  9.35952663e-02, -6.71959043e-01, -2.18338326e-01,
       -1.16354060e+00,  7.23470390e-01,  6.48010731e-01,  7.35838711e-02,
       -5.51448822e-01, -7.33921409e-01,  1.26333997e-01,  4.37926352e-01,
       -2.01008272e+00,  6.53913543e-02,  3.64877939e-01, -6.40782565e-02,
        8.84060487e-02,  4.31548417e-01,  3.86129528e-01,  2.85314769e-01,
        3.89469981e-01, -5.95616877e-01, -2.66712494e-02,  4.05219555e-01,
        5.29134452e-01,  5.63020289e-01,  7.91562349e-02,  2.32243374e-01,
       -3.45054626e-01,  9.59868580e-02,  7.81548083e-01, -1.22057438e-01,
        5.58556497e-01, -1.51628613e-01, -1.49094239e-01,  1.05431366e+00,
       -2.85095364e-01, -1.08268168e-02,  8.46317690e-03, -7.36630321e-01,
       -4.36044782e-01, -1.09612346e-02,  1.19680241e-01, -4.93608713e-01,
       -2.59789377e-01, -4.93155628e-01, -1.09641969e+00,  1.22427940e-03,
       -2.41686434e-01,  3.07442039e-01,  2.58054167e-01, -4.20287609e-01,
        8.10006797e-01, -2.49865681e-01,  5.16568065e-01,  3.30187380e-01,
       -1.70860600e+00,  1.10717738e+00,  8.74224544e-01,  9.10585970e-02,
       -3.44872653e-01, -1.05223797e-01, -3.42680871e-01, -6.33816123e-01,
       -7.40606010e-01,  9.07885075e-01,  1.50419950e-01, -2.95774937e-02,
        5.33285141e-01, -8.89884606e-02,  1.88885932e-03, -5.26352763e-01,
       -4.60462958e-01, -8.98346901e-01, -9.30130780e-01, -8.71662140e-01,
       -4.62210745e-01, -3.74868400e-02,  8.89487490e-02, -3.14910591e-01,
       -2.95265436e-01,  2.57440984e-01,  1.12165904e+00, -4.07135397e-01,
        5.15556395e-01,  6.56725526e-01, -4.53766733e-02,  9.34525579e-02,
        1.96665917e-02,  5.81217885e-01, -6.55660629e-01,  2.17630342e-01,
        3.99800211e-01, -7.11594939e-01, -3.85992855e-01, -4.72876459e-01,
        1.39957620e-02, -4.99945968e-01, -1.15468249e-01,  3.61773781e-02,
       -7.52986789e-01,  1.42092898e-01, -4.32607420e-02, -1.13632846e+00,
        2.23557666e-01,  3.54330927e-01,  3.37925524e-01,  4.51365188e-02,
        4.35933888e-01,  5.54134063e-02, -7.90425092e-02, -3.36585082e-02,
        1.48999006e-01, -3.05866450e-01, -7.90316701e-01,  2.95055568e-01,
       -8.04731846e-01, -9.42065060e-01,  6.03692532e-01, -9.15146470e-02,
        1.22393632e+00, -5.31008951e-02, -1.21099040e-01, -2.04549626e-01,
       -1.24869442e+00, -7.96625912e-02,  8.24638665e-01, -3.72060955e-01,
       -7.38567233e-01, -1.04499698e+00, -1.01952171e+00,  7.48128146e-02,
       -4.50760931e-01,  1.55805886e-01, -8.29298794e-01, -4.57272917e-01,
       -6.91787720e-01,  1.61600739e-01, -2.10935026e-01, -5.20445466e-01,
        1.73945412e-01,  6.77092910e-01, -5.60843587e-01,  9.43865418e-01,
       -8.48158181e-01, -1.38080144e+00, -4.16159540e-01, -1.55344978e-01,
        2.53773361e-01, -3.13634783e-01, -2.39310175e-01, -3.55686426e-01,
        8.15203667e-01,  6.59070432e-01, -1.43646467e+00, -7.52467752e-01,
       -3.21716040e-01, -3.32566917e-01, -1.48018479e+00, -7.13653639e-02,
       -7.73457140e-02,  1.01291525e+00,  8.80545974e-01, -9.03279036e-02,
       -8.65679607e-02,  1.80987492e-01, -7.88121581e-01, -2.40892559e-01,
       -1.34370431e-01,  1.31940639e+00,  4.56786782e-01,  1.19577229e-01,
       -1.70785442e-01, -2.13458493e-01,  5.35219193e-01, -1.70120865e-01,
        5.42463481e-01,  8.13169107e-02,  9.82744515e-01,  3.17285150e-01,
       -5.11080384e-01,  3.50610286e-01, -6.27257049e-01,  6.33217514e-01,
       -5.10222137e-01,  4.07862812e-01, -3.01970243e-01,  7.24187374e-01,
       -4.62492645e-01,  8.37061107e-01,  3.57557654e-01, -9.85393345e-01,
        8.58416110e-02,  1.98524326e-01, -3.36990178e-01, -1.12754953e+00,
       -1.17963421e+00, -9.98154841e-03,  3.79720517e-02,  4.41103518e-01,
        6.36990666e-01, -1.31902501e-01, -1.43147126e-01, -1.93785906e-01,
       -1.48092121e-01, -1.09490407e+00, -9.76871476e-02, -2.96662718e-01,
       -3.32616597e-01, -3.81074240e-03,  4.36100662e-01,  5.00032842e-01,
        9.51889038e-01, -1.25927523e-01,  1.47938207e-01,  4.33320135e-01,
       -7.06925452e-01,  8.51975739e-01,  2.92708904e-01, -8.81360620e-02,
       -4.41896528e-01,  6.98651493e-01,  9.83425975e-01,  2.53567725e-01,
       -9.24312472e-02,  5.31835034e-02,  8.25468361e-01,  7.50907481e-01,
        9.95401084e-01,  9.79320824e-01,  6.57884717e-01, -9.24641430e-01,
       -3.90517145e-01, -1.77759588e-01,  1.27916980e+00, -2.98171222e-01,
       -3.62373054e-01,  4.36610699e-01, -1.79720402e-01, -8.10000420e-01,
        7.29968905e-01,  4.58118856e-01,  4.18992996e-01, -5.79080164e-01,
        3.86602819e-01,  4.83326256e-01,  1.33325309e-01, -1.48050264e-01,
       -6.43170178e-02, -5.63307643e-01,  3.68760884e-01, -4.52007055e-01,
       -7.32959449e-01, -1.99713540e+00,  1.77923739e-02, -2.42328003e-01,
        1.59388757e+00, -4.26847309e-01, -5.59978485e-01,  1.05264066e-02,
        4.96198267e-01, -2.23088376e-02,  4.08750445e-01, -4.80737299e-01,
       -5.68081737e-01, -8.20436180e-01, -4.76190865e-01, -2.39470631e-01,
        1.14199735e-01, -4.51646894e-01,  7.78434932e-01,  4.73831475e-01,
       -5.86858630e-01, -8.52898419e-01, -2.39806660e-02,  4.89012957e-01,
       -4.75367159e-01, -2.32945774e-02, -1.65455900e-02, -2.22341299e-01,
        6.44146919e-01,  8.11915517e-01, -1.29373384e+00,  5.24078012e-02,
       -1.03128588e+00, -8.23341072e-01, -9.01063263e-01,  5.15161395e-01,
       -3.65071356e-01,  5.51766396e-01, -1.37974350e-02,  1.26767886e+00,
        2.80236453e-01, -2.09561080e-01, -3.80236715e-01,  1.12683141e+00,
        1.54411986e-01, -5.96880794e-01,  5.04159808e-01,  2.35550597e-01,
       -2.84491807e-01,  3.79281700e-01, -1.04358055e-01,  8.59665036e-01,
        4.77161348e-01,  7.90461004e-01,  3.31538200e-01, -2.96445072e-01,
        6.68064207e-02, -5.72264135e-01,  2.98637748e-01, -2.12672994e-01,
       -4.53764826e-01,  1.92580968e-01,  1.34764135e-01,  6.31025970e-01,
       -8.98519978e-02, -9.23455417e-01, -1.14112422e-01, -4.09817547e-01,
       -3.42471510e-01,  1.05504847e+00, -6.34744763e-01, -7.82064974e-01,
        5.84862456e-02, -5.85135818e-01,  2.02817604e-01, -4.62332033e-02,
       -4.72066075e-01, -2.60782629e-01,  7.09236979e-01,  9.75550830e-01,
       -1.60618544e-01,  6.75963908e-02, -5.59106171e-01,  6.51606619e-01,
       -7.83934176e-01,  2.85823699e-02,  4.65895712e-01, -6.44486308e-01,
        7.07487762e-01, -1.37532127e+00, -1.04068387e+00, -2.40361288e-01,
       -4.23448503e-01, -9.95084405e-01, -1.36418092e+00, -5.38952231e-01],
      dtype=float32)

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

In [34]:
#calculate cosine similarity between the key_wd and the embedded job titles.

cos_sim = cosine_similarity([key_wd], sentence_embeddings)
cos_sim

array([[0.49784946, 0.37227935, 0.92721355, 0.70583117, 0.46320152,
        0.9426096 , 0.7215086 , 0.6806127 , 0.7215086 , 0.76440686,
        0.4487623 , 0.29949862, 0.3971985 , 0.49784946, 0.49784946,
        0.37227935, 0.92721355, 0.70583117, 0.49784946, 0.37227935,
        0.92721355, 0.70583117, 0.46320152, 0.9426096 , 0.7215086 ,
        0.6806127 , 0.67100704, 0.83371305, 0.67100704, 0.83371305,
        0.49784946, 0.37227935, 0.92721355, 0.70583117, 0.46320152,
        0.9426096 , 0.7215086 , 0.6806127 , 0.7215086 , 0.76440686,
        0.4487623 , 0.29949862, 0.3971985 , 0.49784946, 0.37227935,
        0.92721355, 0.70583117, 0.46320152, 0.9426096 , 0.7215086 ,
        0.6806127 , 0.7215086 , 0.76440686, 0.4487623 , 0.29949862,
        0.3971985 , 0.49784946, 0.92721355, 0.70583117, 0.9426096 ,
        0.6806127 , 0.76440686, 0.44876224, 0.29949862, 0.3971985 ,
        0.7007382 , 0.75128293, 0.6953852 , 0.4491577 , 0.42338023,
        0.5415801 , 0.6560505 , 0.7402716 , 0.78272295, 0.5442034 ,
        0.69621825, 0.6103471 , 0.5381652 , 0.5975433 , 0.56517756,
        0.48132116, 0.80302584, 0.37163407, 0.5379615 , 0.259422  ,
        0.509713  , 0.08629318, 0.6838629 , 0.7035968 , 0.43730503,
        0.3835103 , 0.62829983, 0.16493401, 0.67053866, 0.49145716,
        0.25283498, 0.92721355, 0.65468884, 0.8477609 , 0.50086135,
        0.60929954, 0.45511636, 0.6189587 , 0.48834145]], dtype=float32)

In [35]:
df.fit = np.squeeze(cos_sim) #np.squeeze to reduce the array dim from 2d to 1d

In [36]:
df.head()

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.497849
1,2,Native English Teacher at EPIK (English Progra...,Canada,500+,0.372279
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.927214
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,0.705831
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,0.463202

In [115]:
candidates = df.sort_values('fit', ignore_index=True, ascending=False)
candidates.rename(columns={'fit':'job_fit'}, inplace=True)

candidates

,id,job_title,location,connection,job_fit
0,24,Aspiring Human Resources Specialist,Greater New York City Area,1,0.942610
1,60,Aspiring Human Resources Specialist,Greater New York City Area,1,0.942610
2,6,Aspiring Human Resources Specialist,Greater New York City Area,1,0.942610
3,36,Aspiring Human Resources Specialist,Greater New York City Area,1,0.942610
4,49,Aspiring Human Resources Specialist,Greater New York City Area,1,0.942610
...,...,...,...,...,...
99,12,"SVP, CHRO, Marketing & Communications, CSR Off...","Houston, Texas Area",500+,0.299499
100,85,RRP Brand Portfolio Executive at JTI (Japan To...,Greater Philadelphia Area,500+,0.259422
101,96,Student at Indiana University Kokomo - Busines...,"Lafayette, Indiana",19,0.252835
102,93,Admissions Representative at Community medical...,"Long Beach, California",9,0.164934
103,87,Bachelor of Science in Biology from Victoria U...,"Baltimore, Maryland",40,0.086293

In [116]:
candidates.shape

(104, 5)

## Create a function to use the job title AND location information of a preferred candidate to re-rank the list

In [113]:
# the following function takes the id number of the preferred candidate from the first round and uses that candidate's
# location to rerank the candidates based on the job_title AND location

def rerank (id_num, input_df):
    '''
    input: id_num - id number of the preferred candidate from the first round of screening
    input: input_df - this is the df where the data from the first sceening round is stored
    
    output: df containing the new columns where location similarity values and the average of the job and location
            similarity values are stored
    '''
    # remove the previously created columns in the input df since they will be calculated again in this function
    df = input_df.iloc[:, :4]
    
    #preferred candidate job_title embedding
    cand_job_embedding = model.encode (df[df.id==id_num].iloc[0]['job_title'])
    #preferred candidate location embedding
    cand_loc_embedding = model.encode(df[df.id==id_num].iloc[0]['location'])
    
    # embedding of all the job titles in the input_df
    job_title_embeddings = model.encode(df.job_title)
    # embedding of all the locations in the input_df
    location_embeddings = model.encode(df.location)
    #calculate cos similarities between the location of the preferred candidate and all the candidates in the input_df
    loc_cos_sim = cosine_similarity([cand_loc_embedding], location_embeddings)
    #calculate cos similarities between the job_title of the preferred candidate and all the candidates in the input_df
    job_cos_sim = cosine_similarity([cand_job_embedding], job_title_embeddings)
    #append the cos similarities for job title to the df
    df['job_fit'] = np.squeeze(job_cos_sim)
    #append the cos similarities for location to the df
    df['location_fit'] = np.squeeze(loc_cos_sim)
    #calculate the mean between the job and location cos similarities for each candidate 
    df['job_loc_fit'] = df.iloc[:,4:].mean(axis=1)
    #sort the df based on the cos mean value
    df = df.sort_values('job_loc_fit', ignore_index = True, ascending=False)
    
    return df

In [117]:
# rerank the list based on candidate id 53
output_df = rerank(53, candidates)
output_df

,id,job_title,location,connection,job_fit,location_fit,job_loc_fit
0,53,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,1.000000,1.000000,1.000000
1,40,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,1.000000,1.000000,1.000000
2,62,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,1.000000,1.000000,1.000000
3,10,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,1.000000,1.000000,1.000000
4,68,Human Resources Specialist at Luxottica,Greater New York City Area,500+,0.831415,0.649568,0.740492
...,...,...,...,...,...,...,...
99,19,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.346019,0.315334,0.330677
100,44,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.346019,0.315334,0.330677
101,31,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.346019,0.315334,0.330677
102,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.346019,0.315334,0.330677
103,93,Admissions Representative at Community medical...,"Long Beach, California",9,0.298172,0.305684,0.301928